package grammar

import (
	"fmt"
	"strconv"
	"strings"

	"github.com/odvcencio/gotreesitter/grammargen"
)

// EBNF returns a readable EBNF rendering of the grammar DSL. Lexer precedence
// and parser precedence are described in the generated preamble because EBNF
// does not represent either mechanism.
func EBNF() (string, error) {
	g := Cicada()
	var out strings.Builder
	out.WriteString("(* Generated by go generate ./language/grammar from language/grammar/grammar.go. Do not edit.\n")
	out.WriteString("   Quoted forms are literal terminals; /.../ forms are regular expressions.\n")
	out.WriteString("   Brackets mean optional, braces mean zero-or-more, and parentheses group.\n")
	out.WriteString("   Spaces, tabs, CR, LF, and // comments are ignored between tokens.\n")
	out.WriteString("   Expression operators are left-associative: * and / bind more tightly than + and -.\n")
	out.WriteString("   The lexer uses priority rules for overlapping drum-row tokens; this EBNF lists\n")
	out.WriteString("   their spellings but does not encode lexical priority. Semantic limits are in\n")
	out.WriteString("   edition-1.md. *)\n\n")
	for _, name := range g.RuleOrder {
		rule := g.Rules[name]
		rhs, err := renderEBNF(rule, grammargen.RuleKind(-1))
		if err != nil {
			return "", fmt.Errorf("render production %s: %w", name, err)
		}
		out.WriteString(wrapProduction(name, rhs))
		out.WriteString(" ;\n")
	}
	return out.String(), nil
}

func renderEBNF(rule *grammargen.Rule, parent grammargen.RuleKind) (string, error) {
	if rule == nil {
		return "", fmt.Errorf("nil grammar rule")
	}
	renderChildren := func(separator string) ([]string, error) {
		children := make([]string, len(rule.Children))
		for i, child := range rule.Children {
			value, err := renderEBNF(child, rule.Kind)
			if err != nil {
				return nil, err
			}
			children[i] = value
		}
		return children, nil
	}
	switch rule.Kind {
	case grammargen.RuleString:
		return strconv.Quote(rule.Value), nil
	case grammargen.RulePattern:
		return "/" + rule.Value + "/", nil
	case grammargen.RuleSymbol:
		return rule.Value, nil
	case grammargen.RuleBlank:
		return "ε", nil
	case grammargen.RuleSeq, grammargen.RuleChoice:
		children, err := renderChildren("")
		if err != nil {
			return "", err
		}
		separator := " , "
		if rule.Kind == grammargen.RuleChoice {
			separator = " | "
		}
		value := strings.Join(children, separator)
		if rule.Kind == grammargen.RuleChoice && parent == grammargen.RuleSeq {
			value = "(" + value + ")"
		}
		return value, nil
	case grammargen.RuleRepeat, grammargen.RuleRepeat1, grammargen.RuleOptional:
		if len(rule.Children) != 1 {
			return "", fmt.Errorf("%v has %d children, want one", rule.Kind, len(rule.Children))
		}
		child, err := renderEBNF(rule.Children[0], rule.Kind)
		if err != nil {
			return "", err
		}
		switch rule.Kind {
		case grammargen.RuleRepeat:
			return "{ " + child + " }", nil
		case grammargen.RuleRepeat1:
			return child + " , { " + child + " }", nil
		default:
			return "[ " + child + " ]", nil
		}
	case grammargen.RuleToken, grammargen.RuleImmToken, grammargen.RuleField,
		grammargen.RulePrec, grammargen.RulePrecLeft, grammargen.RulePrecRight,
		grammargen.RulePrecDynamic, grammargen.RuleAlias:
		if len(rule.Children) != 1 {
			return "", fmt.Errorf("%v has %d children, want one", rule.Kind, len(rule.Children))
		}
		return renderEBNF(rule.Children[0], parent)
	default:
		return "", fmt.Errorf("unsupported grammargen rule kind %d", rule.Kind)
	}
}

func wrapProduction(name, rhs string) string {
	const width = 100
	prefix := name + " ::= "
	if len(prefix)+len(rhs) <= width {
		return prefix + rhs
	}
	indent := strings.Repeat(" ", len(prefix))
	segments, separators := topLevelSegments(rhs)
	if len(segments) == 1 {
		return prefix + rhs
	}
	var out strings.Builder
	line := prefix + segments[0]
	for i, separator := range separators {
		addition := " " + separator + " " + segments[i+1]
		if len(line)+len(addition) > width {
			out.WriteString(line)
			out.WriteString(" " + separator)
			out.WriteByte('\n')
			line = indent + segments[i+1]
		} else {
			line += addition
		}
	}
	out.WriteString(line)
	return out.String()
}

// topLevelSegments returns break points after commas and alternatives that are
// outside terminals and grouping.
func topLevelSegments(rhs string) ([]string, []string) {
	var segments, separators []string
	start := 0
	paren, bracket, brace := 0, 0, 0
	quoted, regex, escaped := false, false, false
	for i := 0; i < len(rhs); i++ {
		c := rhs[i]
		if escaped {
			escaped = false
			continue
		}
		if c == '\\' && (quoted || regex) {
			escaped = true
			continue
		}
		if quoted {
			if c == '"' {
				quoted = false
			}
			continue
		}
		if regex {
			if c == '/' {
				regex = false
			}
			continue
		}
		if c == '"' {
			quoted = true
			continue
		}
		if c == '/' && (i == 0 || rhs[i-1] == ' ' || rhs[i-1] == '(' || rhs[i-1] == '|') {
			regex = true
			continue
		}
		switch c {
		case '(':
			paren++
		case ')':
			paren--
		case '[':
			bracket++
		case ']':
			bracket--
		case '{':
			brace++
		case '}':
			brace--
		}
		if paren != 0 || bracket != 0 || brace != 0 {
			continue
		}
		separator := ""
		end := i + 1
		if c == ',' && i+1 < len(rhs) && rhs[i+1] == ' ' {
			separator = ","
			end = i + 2
		} else if c == '|' && i > 0 && i+1 < len(rhs) && rhs[i-1] == ' ' && rhs[i+1] == ' ' {
			separator = "|"
			end = i + 2
		} else {
			continue
		}
		segments = append(segments, strings.TrimRight(rhs[start:i], " "))
		separators = append(separators, separator)
		start = end
		i = end - 1
	}
	segments = append(segments, rhs[start:])
	return segments, separators
}
