// Code generated by go generate; DO NOT EDIT.
package ui

import gosx "m31labs.dev/gosx"

type ShellProps struct {
	Title      string
	Filename   string
	Tempo      string
	Key        string
	Message    string
	HasMessage bool
}

func Shell(props ShellProps, children ...gosx.Node) gosx.Node {
	return gosx.El("div", gosx.Attrs(gosx.Attr("class", "studio")), gosx.El("a", gosx.Attrs(gosx.Attr("class", "skip"), gosx.Attr("href", "#workspace")), gosx.Text("Skip to workspace")), gosx.El("header", gosx.Attrs(gosx.Attr("class", "masthead")), gosx.El("a", gosx.Attrs(gosx.Attr("class", "brand"), gosx.Attr("href", "/")), gosx.Text("CICADA "), gosx.El("span", gosx.Text("STUDIO"))), gosx.El("div", gosx.Attrs(gosx.Attr("class", "score-title")), gosx.El("h1", gosx.Expr(props.Title)), gosx.El("span", gosx.Attrs(gosx.Attr("class", "muted")), gosx.Expr(props.Filename))), gosx.El("div", gosx.Attrs(gosx.Attr("class", "score-meta")), gosx.El("span", gosx.Expr(props.Tempo), gosx.Text(" BPM")), gosx.El("span", gosx.Expr(props.Key)), gosx.El("span", gosx.Attrs(gosx.Attr("class", "engine-label")), gosx.Text("TYMBAL")))), gosx.If(props.HasMessage, gosx.Fragment(gosx.El("p", gosx.Attrs(gosx.Attr("class", "notice"), gosx.Attr("role", "status")), gosx.Expr(props.Message)))), gosx.El("div", gosx.Attrs(gosx.Attr("class", "notices"), gosx.BoolAttr("data-gosx-toast-host"), gosx.Attr("role", "status"), gosx.Attr("aria-live", "polite"))), gosx.Expr(children), gosx.El("footer", gosx.Text("Score first. Sound follows.")))
}

type PanelProps struct {
	ID          string
	Title       string
	Description string
}

func Panel(props PanelProps, children ...gosx.Node) gosx.Node {
	return gosx.El("section", gosx.Attrs(gosx.Attr("class", "panel"), gosx.Attr("id", props.ID), gosx.Attr("aria-label", props.Title)), gosx.El("div", gosx.Attrs(gosx.Attr("class", "panel-heading")), gosx.El("h2", gosx.Expr(props.Title)), gosx.El("p", gosx.Attrs(gosx.Attr("class", "muted")), gosx.Expr(props.Description))), gosx.Expr(children))
}

type FormProps struct {
	Action   string
	CSRF     string
	Revision string
	ReturnTo string
	Class    string
}

func Form(props FormProps, children ...gosx.Node) gosx.Node {
	return gosx.El("form", gosx.Attrs(gosx.Attr("method", "post"), gosx.Attr("action", props.Action), gosx.BoolAttr("data-gosx-managed"), gosx.Attr("class", props.Class)), gosx.El("input", gosx.Attrs(gosx.Attr("type", "hidden"), gosx.Attr("name", "csrf_token"), gosx.Attr("value", props.CSRF))), gosx.El("input", gosx.Attrs(gosx.Attr("type", "hidden"), gosx.Attr("name", "revision"), gosx.Attr("value", props.Revision))), gosx.El("input", gosx.Attrs(gosx.Attr("type", "hidden"), gosx.Attr("name", "__gosx_return_to"), gosx.Attr("value", props.ReturnTo))), gosx.Expr(children))
}

type StepProps struct {
	Label   string
	Text    string
	Active  bool
	Index   int
	Pattern string
	Lane    string
}

func Step(props StepProps, children ...gosx.Node) gosx.Node {
	return gosx.El("button", gosx.Attrs(gosx.Attr("class", "step"), gosx.Attr("type", "submit"), gosx.Attr("name", "step"), gosx.Attr("value", props.Index), gosx.Attr("aria-label", props.Label), gosx.Attr("aria-pressed", props.Active), gosx.Attr("data-active", props.Active), gosx.Attr("data-pattern", props.Pattern), gosx.Attr("data-lane", props.Lane)), gosx.Expr(props.Text))
}

type TransportProps struct {
	Playing bool
	Bar     int64
	Step    int64
	Backend string
	Error   string
}

func Position(props TransportProps, children ...gosx.Node) gosx.Node {
	return gosx.El("div", gosx.Attrs(gosx.Attr("class", "position"), gosx.Attr("data-gosx-live-src", "/api/transport"), gosx.Attr("data-gosx-live-interval", "1s")), gosx.El("span", gosx.Attrs(gosx.Attr("class", "position-label")), gosx.Text("BAR "), gosx.El("b", gosx.Attrs(gosx.Attr("data-gosx-live-bind", "bar")), gosx.Expr(props.Bar))), gosx.El("span", gosx.Attrs(gosx.Attr("class", "position-label")), gosx.Text("STEP "), gosx.El("b", gosx.Attrs(gosx.Attr("data-gosx-live-bind", "step")), gosx.Expr(props.Step))), gosx.El("span", gosx.Attrs(gosx.Attr("class", "muted"), gosx.Attr("data-gosx-live-bind", "activeBackend")), gosx.Expr(props.Backend)), gosx.El("span", gosx.Attrs(gosx.Attr("class", "error"), gosx.Attr("data-gosx-live-bind", "error")), gosx.Expr(props.Error)))
}
