// Code generated by cmd/paramgen; DO NOT EDIT.
package kernel

type ParamID uint16
type ParamSpec struct {
	ID                                              ParamID
	Name, Path, Scope, Source, Unit, Curve, Persist string
	Min, Max, Default, DisplayStep                  float32
	SmoothingMS                                     float32
	Live, Automatable, Off                          bool
}

const (
	ParamMixGain             ParamID = 0
	ParamMixPan              ParamID = 1
	ParamMixSendA            ParamID = 2
	ParamMixSendB            ParamID = 3
	ParamMixMute             ParamID = 4
	ParamMixSolo             ParamID = 5
	ParamMixSendPre          ParamID = 6
	ParamMixBus              ParamID = 7
	ParamMixInsert           ParamID = 8
	ParamFxDriveShape        ParamID = 9
	ParamFxDriveGain         ParamID = 10
	ParamFxDriveTone         ParamID = 11
	ParamFxDriveMix          ParamID = 12
	ParamFxDelayTime         ParamID = 13
	ParamFxDelayFeedback     ParamID = 14
	ParamFxDelayDamp         ParamID = 15
	ParamFxDelayPingpong     ParamID = 16
	ParamFxDelayWidth        ParamID = 17
	ParamFxDelayMix          ParamID = 18
	ParamFxReverbSize        ParamID = 19
	ParamFxReverbDecay       ParamID = 20
	ParamFxReverbDamp        ParamID = 21
	ParamFxReverbHighpass    ParamID = 22
	ParamFxReverbPredelay    ParamID = 23
	ParamFxReverbMix         ParamID = 24
	ParamFxCompDetect        ParamID = 25
	ParamFxCompThreshold     ParamID = 26
	ParamFxCompRatio         ParamID = 27
	ParamFxCompKnee          ParamID = 28
	ParamFxCompAttack        ParamID = 29
	ParamFxCompRelease       ParamID = 30
	ParamFxCompMakeup        ParamID = 31
	ParamFxCompMix           ParamID = 32
	ParamFxCompSidechain     ParamID = 33
	ParamAcidTune            ParamID = 34
	ParamAcidFine            ParamID = 35
	ParamAcidWave            ParamID = 36
	ParamAcidPw              ParamID = 37
	ParamAcidDetune          ParamID = 38
	ParamAcidSub             ParamID = 39
	ParamAcidCutoff          ParamID = 40
	ParamAcidReso            ParamID = 41
	ParamAcidEnvmod          ParamID = 42
	ParamAcidDecay           ParamID = 43
	ParamAcidAccent          ParamID = 44
	ParamAcidDrive           ParamID = 45
	ParamAcidRelease         ParamID = 46
	ParamAcidSlide           ParamID = 47
	ParamAcidGate            ParamID = 48
	ParamAcidFilter          ParamID = 49
	ParamAcidSavage          ParamID = 50
	ParamAcidOctave          ParamID = 51
	ParamDrumBdTune          ParamID = 52
	ParamDrumBdDecay         ParamID = 53
	ParamDrumBdSweep         ParamID = 54
	ParamDrumBdSweepTime     ParamID = 55
	ParamDrumBdClick         ParamID = 56
	ParamDrumBdDrive         ParamID = 57
	ParamDrumBdLevel         ParamID = 58
	ParamDrumBdPan           ParamID = 59
	ParamDrumSdTune          ParamID = 60
	ParamDrumSdTone          ParamID = 61
	ParamDrumSdMix           ParamID = 62
	ParamDrumSdSnappy        ParamID = 63
	ParamDrumSdDecay         ParamID = 64
	ParamDrumSdLevel         ParamID = 65
	ParamDrumSdPan           ParamID = 66
	ParamDrumChTune          ParamID = 67
	ParamDrumChTone          ParamID = 68
	ParamDrumChDecay         ParamID = 69
	ParamDrumChMetal         ParamID = 70
	ParamDrumChLevel         ParamID = 71
	ParamDrumChPan           ParamID = 72
	ParamDrumOhTune          ParamID = 73
	ParamDrumOhTone          ParamID = 74
	ParamDrumOhDecay         ParamID = 75
	ParamDrumOhMetal         ParamID = 76
	ParamDrumOhLevel         ParamID = 77
	ParamDrumOhPan           ParamID = 78
	ParamDrumCpTone          ParamID = 79
	ParamDrumCpDecay         ParamID = 80
	ParamDrumCpSpread        ParamID = 81
	ParamDrumCpLevel         ParamID = 82
	ParamDrumCpPan           ParamID = 83
	ParamDrumRsTune          ParamID = 84
	ParamDrumRsDecay         ParamID = 85
	ParamDrumRsLevel         ParamID = 86
	ParamDrumRsPan           ParamID = 87
	ParamDrumLtTune          ParamID = 88
	ParamDrumLtDecay         ParamID = 89
	ParamDrumLtSweep         ParamID = 90
	ParamDrumLtLevel         ParamID = 91
	ParamDrumLtPan           ParamID = 92
	ParamDrumMtTune          ParamID = 93
	ParamDrumMtDecay         ParamID = 94
	ParamDrumMtSweep         ParamID = 95
	ParamDrumMtLevel         ParamID = 96
	ParamDrumMtPan           ParamID = 97
	ParamDrumHtTune          ParamID = 98
	ParamDrumHtDecay         ParamID = 99
	ParamDrumHtSweep         ParamID = 100
	ParamDrumHtLevel         ParamID = 101
	ParamDrumHtPan           ParamID = 102
	ParamDrumCbTune          ParamID = 103
	ParamDrumCbDecay         ParamID = 104
	ParamDrumCbLevel         ParamID = 105
	ParamDrumCbPan           ParamID = 106
	ParamDrumCyTune          ParamID = 107
	ParamDrumCyDecay         ParamID = 108
	ParamDrumCyTone          ParamID = 109
	ParamDrumCyLevel         ParamID = 110
	ParamDrumCyPan           ParamID = 111
	ParamDrumCpTune          ParamID = 112
	ParamGlobalTempo         ParamID = 113
	ParamGlobalTranspose     ParamID = 114
	ParamMixBusLevel         ParamID = 115
	ParamMixBusPan           ParamID = 116
	ParamMixBusMute          ParamID = 117
	ParamMixBusSolo          ParamID = 118
	ParamMixBusInsert        ParamID = 119
	ParamMixBusSendDelay     ParamID = 120
	ParamMixBusSendReverb    ParamID = 121
	ParamMixBusOut           ParamID = 122
	ParamMixMasterLevel      ParamID = 123
	ParamMixMasterPan        ParamID = 124
	ParamMixMasterMute       ParamID = 125
	ParamMixMasterSolo       ParamID = 126
	ParamMixMasterInsert     ParamID = 127
	ParamMixMasterSendDelay  ParamID = 128
	ParamMixMasterSendReverb ParamID = 129
	ParamMixMasterOut        ParamID = 130
	ParamPianoSustain        ParamID = 131
	ParamCount                       = 132
)

var Params = [...]ParamSpec{
	{0, "mix.gain", "level", "track", "level", "dB", "fader", "source", -60, 6, -6, 0.1, 5, true, true, true},
	{1, "mix.pan", "pan", "track", "pan", "", "linear", "source", -1, 1, 0, 0.01, 5, true, true, false},
	{2, "mix.send_a", "send.delay", "track", "send", "", "linear", "source", 0, 1, 0, 0.01, 5, true, true, false},
	{3, "mix.send_b", "send.reverb", "track", "send", "", "linear", "source", 0, 1, 0, 0.01, 5, true, true, false},
	{4, "mix.mute", "mute", "track", "mute", "", "toggle", "source", 0, 1, 0, 0.01, 10, true, false, false},
	{5, "mix.solo", "solo", "track", "solo", "", "toggle", "source", 0, 1, 0, 0.01, 10, true, false, false},
	{6, "mix.send_pre", "send_pre", "track", "send_pre", "", "toggle", "source", 0, 1, 0, 0.01, 0, false, false, false},
	{7, "mix.bus", "bus", "track", "bus", "", "enum", "source", 0, 1, 0, 0.01, 0, false, false, false},
	{8, "mix.insert", "insert", "track", "insert", "", "enum", "source", 0, 1, 0, 0.01, 0, false, false, false},
	{9, "fx.drive.shape", "drive.shape", "global", "shape", "", "enum", "source", 0, 3, 0, 0.01, 0, false, false, false},
	{10, "fx.drive.gain", "drive.gain", "global", "gain", "dB", "linear", "source", 0, 36, 0, 0.1, 5, true, true, false},
	{11, "fx.drive.tone", "drive.tone", "global", "tone", "Hz", "log", "source", 1000, 20000, 12000, 1, 5, true, true, false},
	{12, "fx.drive.mix", "drive.mix", "global", "mix", "ratio", "linear", "source", 0, 1, 1, 0.01, 5, true, true, false},
	{13, "fx.delay.time", "delay.time", "global", "time", "ms", "log", "source", 1, 2000, 250, 0.1, 20, true, true, false},
	{14, "fx.delay.feedback", "delay.feedback", "global", "feedback", "ratio", "linear", "source", 0, 0.95, 0.35, 0.01, 5, true, true, false},
	{15, "fx.delay.damp", "delay.damp", "global", "damp", "Hz", "log", "source", 1000, 16000, 6000, 1, 5, true, true, false},
	{16, "fx.delay.pingpong", "delay.pingpong", "global", "pingpong", "", "toggle", "source", 0, 1, 0, 0.01, 5, true, true, false},
	{17, "fx.delay.width", "delay.width", "global", "width", "ratio", "linear", "source", 0, 1, 1, 0.01, 5, true, true, false},
	{18, "fx.delay.mix", "delay.mix", "global", "mix", "ratio", "linear", "source", 0, 1, 1, 0.01, 5, true, true, false},
	{19, "fx.reverb.size", "reverb.size", "global", "size", "ratio", "linear", "source", 0.5, 1.5, 1, 0.01, 5, true, true, false},
	{20, "fx.reverb.decay", "reverb.decay", "global", "decay", "ms", "log", "source", 300, 12000, 2400, 0.1, 5, true, true, false},
	{21, "fx.reverb.damp", "reverb.damp", "global", "damp", "Hz", "log", "source", 2000, 16000, 8000, 1, 5, true, true, false},
	{22, "fx.reverb.highpass", "reverb.highpass", "global", "highpass", "Hz", "log", "source", 40, 400, 120, 1, 5, true, true, false},
	{23, "fx.reverb.predelay", "reverb.predelay", "global", "predelay", "ms", "linear", "source", 0, 200, 0, 0.1, 5, true, true, false},
	{24, "fx.reverb.mix", "reverb.mix", "global", "mix", "ratio", "linear", "source", 0, 1, 1, 0.01, 5, true, true, false},
	{25, "fx.comp.detect", "comp.detect", "global", "detect", "", "enum", "source", 0, 1, 0, 0.01, 0, false, false, false},
	{26, "fx.comp.threshold", "comp.threshold", "global", "threshold", "dB", "linear", "source", -40, 0, -18, 0.1, 5, true, true, false},
	{27, "fx.comp.ratio", "comp.ratio", "global", "ratio", "ratio", "linear", "source", 1, 20, 4, 0.01, 5, true, true, false},
	{28, "fx.comp.knee", "comp.knee", "global", "knee", "dB", "linear", "source", 0, 12, 6, 0.1, 5, true, true, false},
	{29, "fx.comp.attack", "comp.attack", "global", "attack", "ms", "log", "source", 0.1, 100, 10, 0.1, 5, true, true, false},
	{30, "fx.comp.release", "comp.release", "global", "release", "ms", "log", "source", 10, 1000, 100, 0.1, 5, true, true, false},
	{31, "fx.comp.makeup", "comp.makeup", "global", "makeup", "dB", "linear", "source", -24, 24, 0, 0.1, 5, true, true, false},
	{32, "fx.comp.mix", "comp.mix", "global", "mix", "ratio", "linear", "source", 0, 1, 1, 0.01, 5, true, true, false},
	{33, "fx.comp.sidechain", "comp.sidechain", "global", "sidechain", "", "enum", "source", 0, 1, 0, 0.01, 0, false, false, false},
	{34, "acid.tune", "tune", "track", "tune", "", "linear", "source", -12, 12, 0, 0.01, 5, false, false, false},
	{35, "acid.fine", "fine", "track", "fine", "", "linear", "source", -100, 100, 0, 0.01, 5, false, false, false},
	{36, "acid.wave", "wave", "track", "wave", "", "linear", "source", 0, 1, 0, 0.01, 5, false, false, false},
	{37, "acid.pw", "pw", "track", "pw", "", "linear", "source", 0.1, 0.9, 0.5, 0.01, 5, false, false, false},
	{38, "acid.detune", "detune", "track", "detune", "", "linear", "source", 0, 50, 0, 0.01, 5, false, false, false},
	{39, "acid.sub", "sub", "track", "sub", "", "linear", "source", 0, 1, 0, 0.01, 5, false, false, false},
	{40, "acid.cutoff", "cutoff", "track", "cutoff", "Hz", "log", "source", 20, 8000, 600, 1, 3, true, true, false},
	{41, "acid.reso", "reso", "track", "reso", "", "linear", "source", 0, 1, 0.55, 0.01, 5, true, true, false},
	{42, "acid.envmod", "envmod", "track", "envmod", "", "linear", "source", 0, 1, 0.6, 0.01, 5, true, true, false},
	{43, "acid.decay", "decay", "track", "decay", "ms", "log", "source", 100, 3000, 400, 0.1, 5, true, true, false},
	{44, "acid.accent", "accent", "track", "accent", "", "linear", "source", 0, 1, 0.7, 0.01, 5, true, true, false},
	{45, "acid.drive", "drive", "track", "drive", "", "linear", "source", 0, 1, 0.2, 0.01, 5, false, false, false},
	{46, "acid.release", "release", "track", "release", "ms", "log", "source", 5, 500, 30, 0.1, 5, false, false, false},
	{47, "acid.slide", "slide", "track", "slide", "ms", "log", "source", 20, 200, 60, 0.1, 5, false, false, false},
	{48, "acid.gate", "gate", "track", "gate", "", "linear", "source", 10, 100, 55, 0.01, 5, false, false, false},
	{49, "acid.filter", "filter", "track", "filter", "", "enum", "source", 0, 1, 0, 0.01, 0, false, false, false},
	{50, "acid.savage", "savage", "track", "savage", "", "toggle", "source", 0, 1, 0, 0.01, 0, false, false, false},
	{51, "acid.octave", "octave", "track", "octave", "", "enum", "source", 0, 6, 2, 0.01, 0, false, false, false},
	{52, "drum.bd.tune", "bd_tune", "track", "bd_tune", "Hz", "log", "source", 40, 120, 55, 1, 5, true, true, false},
	{53, "drum.bd.decay", "bd_decay", "track", "bd_decay", "ms", "log", "source", 80, 1500, 400, 0.1, 5, true, true, false},
	{54, "drum.bd.sweep", "bd_sweep", "track", "bd_sweep", "", "linear", "source", 1, 8, 4, 0.01, 5, false, false, false},
	{55, "drum.bd.sweep_time", "bd_sweep_time", "track", "bd_sweep_time", "ms", "log", "source", 10, 80, 30, 0.1, 5, false, false, false},
	{56, "drum.bd.click", "bd_click", "track", "bd_click", "ratio", "linear", "source", 0, 1, 0.3, 0.01, 5, false, false, false},
	{57, "drum.bd.drive", "bd_drive", "track", "bd_drive", "ratio", "linear", "source", 0, 1, 0.2, 0.01, 5, false, false, false},
	{58, "drum.bd.level", "bd_level", "track", "bd_level", "dB", "fader", "source", -60, 6, -6, 0.1, 5, true, true, true},
	{59, "drum.bd.pan", "bd_pan", "track", "bd_pan", "", "linear", "source", -1, 1, 0, 0.01, 5, true, true, false},
	{60, "drum.sd.tune", "sd_tune", "track", "sd_tune", "ratio", "linear", "source", 0.7, 1.4, 1, 0.01, 5, true, true, false},
	{61, "drum.sd.tone", "sd_tone", "track", "sd_tone", "ratio", "linear", "source", 0.5, 2, 1, 0.01, 5, false, false, false},
	{62, "drum.sd.mix", "sd_mix", "track", "sd_mix", "ratio", "linear", "source", 0, 1, 0.6, 0.01, 5, false, false, false},
	{63, "drum.sd.snappy", "sd_snappy", "track", "sd_snappy", "ms", "log", "source", 60, 400, 180, 0.1, 5, false, false, false},
	{64, "drum.sd.decay", "sd_decay", "track", "sd_decay", "ms", "log", "source", 40, 300, 90, 0.1, 5, true, true, false},
	{65, "drum.sd.level", "sd_level", "track", "sd_level", "dB", "fader", "source", -60, 6, -6, 0.1, 5, true, true, true},
	{66, "drum.sd.pan", "sd_pan", "track", "sd_pan", "", "linear", "source", -1, 1, 0, 0.01, 5, true, true, false},
	{67, "drum.ch.tune", "ch_tune", "track", "ch_tune", "ratio", "linear", "source", 0.8, 1.25, 1, 0.01, 5, true, true, false},
	{68, "drum.ch.tone", "ch_tone", "track", "ch_tone", "Hz", "log", "source", 5000, 10000, 7500, 1, 5, false, false, false},
	{69, "drum.ch.decay", "ch_decay", "track", "ch_decay", "ms", "log", "source", 20, 150, 60, 0.1, 5, true, true, false},
	{70, "drum.ch.metal", "ch_metal", "track", "ch_metal", "", "toggle", "source", 0, 1, 0, 0.01, 5, false, false, false},
	{71, "drum.ch.level", "ch_level", "track", "ch_level", "dB", "fader", "source", -60, 6, -6, 0.1, 5, true, true, true},
	{72, "drum.ch.pan", "ch_pan", "track", "ch_pan", "", "linear", "source", -1, 1, 0, 0.01, 5, true, true, false},
	{73, "drum.oh.tune", "oh_tune", "track", "oh_tune", "ratio", "linear", "source", 0.8, 1.25, 1, 0.01, 5, true, true, false},
	{74, "drum.oh.tone", "oh_tone", "track", "oh_tone", "Hz", "log", "source", 5000, 10000, 7500, 1, 5, false, false, false},
	{75, "drum.oh.decay", "oh_decay", "track", "oh_decay", "ms", "log", "source", 150, 1200, 400, 0.1, 5, true, true, false},
	{76, "drum.oh.metal", "oh_metal", "track", "oh_metal", "", "toggle", "source", 0, 1, 0, 0.01, 5, false, false, false},
	{77, "drum.oh.level", "oh_level", "track", "oh_level", "dB", "fader", "source", -60, 6, -6, 0.1, 5, true, true, true},
	{78, "drum.oh.pan", "oh_pan", "track", "oh_pan", "", "linear", "source", -1, 1, 0, 0.01, 5, true, true, false},
	{79, "drum.cp.tone", "cp_tone", "track", "cp_tone", "Hz", "log", "source", 700, 2000, 1100, 1, 5, false, false, false},
	{80, "drum.cp.decay", "cp_decay", "track", "cp_decay", "ms", "log", "source", 60, 400, 120, 0.1, 5, true, true, false},
	{81, "drum.cp.spread", "cp_spread", "track", "cp_spread", "ms", "log", "source", 6, 16, 10, 0.1, 5, false, false, false},
	{82, "drum.cp.level", "cp_level", "track", "cp_level", "dB", "fader", "source", -60, 6, -6, 0.1, 5, true, true, true},
	{83, "drum.cp.pan", "cp_pan", "track", "cp_pan", "", "linear", "source", -1, 1, 0, 0.01, 5, true, true, false},
	{84, "drum.rs.tune", "rs_tune", "track", "rs_tune", "ratio", "linear", "source", 0.7, 1.4, 1, 0.01, 5, true, true, false},
	{85, "drum.rs.decay", "rs_decay", "track", "rs_decay", "ms", "log", "source", 4, 50, 12, 0.1, 5, true, true, false},
	{86, "drum.rs.level", "rs_level", "track", "rs_level", "dB", "fader", "source", -60, 6, -6, 0.1, 5, true, true, true},
	{87, "drum.rs.pan", "rs_pan", "track", "rs_pan", "", "linear", "source", -1, 1, 0, 0.01, 5, true, true, false},
	{88, "drum.lt.tune", "lt_tune", "track", "lt_tune", "ratio", "linear", "source", 0.6674199270850172, 1.4983070768766815, 1, 0.01, 5, true, true, false},
	{89, "drum.lt.decay", "lt_decay", "track", "lt_decay", "ms", "log", "source", 80, 1000, 250, 0.1, 5, true, true, false},
	{90, "drum.lt.sweep", "lt_sweep", "track", "lt_sweep", "ratio", "linear", "source", 0, 2, 0.4, 0.01, 5, false, false, false},
	{91, "drum.lt.level", "lt_level", "track", "lt_level", "dB", "fader", "source", -60, 6, -6, 0.1, 5, true, true, true},
	{92, "drum.lt.pan", "lt_pan", "track", "lt_pan", "", "linear", "source", -1, 1, 0, 0.01, 5, true, true, false},
	{93, "drum.mt.tune", "mt_tune", "track", "mt_tune", "ratio", "linear", "source", 0.6674199270850172, 1.4983070768766815, 1, 0.01, 5, true, true, false},
	{94, "drum.mt.decay", "mt_decay", "track", "mt_decay", "ms", "log", "source", 80, 1000, 250, 0.1, 5, true, true, false},
	{95, "drum.mt.sweep", "mt_sweep", "track", "mt_sweep", "ratio", "linear", "source", 0, 2, 0.4, 0.01, 5, false, false, false},
	{96, "drum.mt.level", "mt_level", "track", "mt_level", "dB", "fader", "source", -60, 6, -6, 0.1, 5, true, true, true},
	{97, "drum.mt.pan", "mt_pan", "track", "mt_pan", "", "linear", "source", -1, 1, 0, 0.01, 5, true, true, false},
	{98, "drum.ht.tune", "ht_tune", "track", "ht_tune", "ratio", "linear", "source", 0.6674199270850172, 1.4983070768766815, 1, 0.01, 5, true, true, false},
	{99, "drum.ht.decay", "ht_decay", "track", "ht_decay", "ms", "log", "source", 80, 1000, 250, 0.1, 5, true, true, false},
	{100, "drum.ht.sweep", "ht_sweep", "track", "ht_sweep", "ratio", "linear", "source", 0, 2, 0.4, 0.01, 5, false, false, false},
	{101, "drum.ht.level", "ht_level", "track", "ht_level", "dB", "fader", "source", -60, 6, -6, 0.1, 5, true, true, true},
	{102, "drum.ht.pan", "ht_pan", "track", "ht_pan", "", "linear", "source", -1, 1, 0, 0.01, 5, true, true, false},
	{103, "drum.cb.tune", "cb_tune", "track", "cb_tune", "ratio", "linear", "source", 0.7, 1.4, 1, 0.01, 5, true, true, false},
	{104, "drum.cb.decay", "cb_decay", "track", "cb_decay", "ms", "log", "source", 40, 400, 120, 0.1, 5, true, true, false},
	{105, "drum.cb.level", "cb_level", "track", "cb_level", "dB", "fader", "source", -60, 6, -6, 0.1, 5, true, true, true},
	{106, "drum.cb.pan", "cb_pan", "track", "cb_pan", "", "linear", "source", -1, 1, 0, 0.01, 5, true, true, false},
	{107, "drum.cy.tune", "cy_tune", "track", "cy_tune", "ratio", "linear", "source", 0.8, 1.25, 1, 0.01, 5, true, true, false},
	{108, "drum.cy.decay", "cy_decay", "track", "cy_decay", "ms", "log", "source", 500, 4000, 1500, 0.1, 5, true, true, false},
	{109, "drum.cy.tone", "cy_tone", "track", "cy_tone", "ratio", "linear", "source", 0.5, 2, 1, 0.01, 5, false, false, false},
	{110, "drum.cy.level", "cy_level", "track", "cy_level", "dB", "fader", "source", -60, 6, -6, 0.1, 5, true, true, true},
	{111, "drum.cy.pan", "cy_pan", "track", "cy_pan", "", "linear", "source", -1, 1, 0, 0.01, 5, true, true, false},
	{112, "drum.cp.tune", "cp_tune", "track", "cp_tune", "ratio", "linear", "source", 0.5, 2, 1, 0.01, 5, true, true, false},
	{113, "global.tempo", "tempo", "global", "tempo", "BPM", "linear", "source", 20, 300, 130, 0.1, 5, false, false, false},
	{114, "global.transpose", "transpose", "global", "transpose", "semitone", "linear", "source", -24, 24, 0, 1, 5, false, false, false},
	{115, "mix.bus.level", "level", "bus", "level", "dB", "fader", "source", -60, 6, -3, 0.01, 0, false, false, false},
	{116, "mix.bus.pan", "pan", "bus", "pan", "", "linear", "source", -1, 1, 0, 0.01, 0, false, false, false},
	{117, "mix.bus.mute", "mute", "bus", "mute", "", "toggle", "source", 0, 1, 0, 0.01, 0, false, false, false},
	{118, "mix.bus.solo", "solo", "bus", "solo", "", "toggle", "source", 0, 1, 0, 0.01, 0, false, false, false},
	{119, "mix.bus.insert", "insert", "bus", "insert", "", "enum", "source", 0, 1, 0, 0.01, 0, false, false, false},
	{120, "mix.bus.send.delay", "send.delay", "bus", "send", "ratio", "linear", "source", 0, 1, 0, 0.01, 0, false, false, false},
	{121, "mix.bus.send.reverb", "send.reverb", "bus", "send", "ratio", "linear", "source", 0, 1, 0, 0.01, 0, false, false, false},
	{122, "mix.bus.out", "out", "bus", "out", "", "enum", "source", 0, 1, 0, 0.01, 0, false, false, false},
	{123, "mix.master.level", "level", "master", "level", "dB", "fader", "source", -60, 6, 0, 0.01, 0, false, false, false},
	{124, "mix.master.pan", "pan", "master", "pan", "", "linear", "source", -1, 1, 0, 0.01, 0, false, false, false},
	{125, "mix.master.mute", "mute", "master", "mute", "", "toggle", "source", 0, 1, 0, 0.01, 0, false, false, false},
	{126, "mix.master.solo", "solo", "master", "solo", "", "toggle", "source", 0, 1, 0, 0.01, 0, false, false, false},
	{127, "mix.master.insert", "insert", "master", "insert", "", "enum", "source", 0, 1, 0, 0.01, 0, false, false, false},
	{128, "mix.master.send.delay", "send.delay", "master", "send", "ratio", "linear", "source", 0, 1, 0, 0.01, 0, false, false, false},
	{129, "mix.master.send.reverb", "send.reverb", "master", "send", "ratio", "linear", "source", 0, 1, 0, 0.01, 0, false, false, false},
	{130, "mix.master.out", "out", "master", "out", "", "enum", "source", 0, 1, 0, 0.01, 0, false, false, false},
	{131, "piano.sustain", "sustain", "track", "sustain", "ratio", "linear", "source", 0, 1, 0, 0.01, 0, true, true, false},
}

func Param(id ParamID) (ParamSpec, bool) {
	if int(id) >= len(Params) {
		return ParamSpec{}, false
	}
	return Params[id], true
}
func FindParam(name string) (ParamID, bool) {
	for i := range Params {
		if Params[i].Name == name {
			return ParamID(i), true
		}
	}
	return 0, false
}
