// Code generated by cmd/paramgen; DO NOT EDIT.
package kernel

type ParamID uint16
type ParamSpec struct {
	ID                                        ParamID
	Name, Scope, Source, Unit, Curve, Persist string
	Min, Max, Default                         float32
	SmoothingMS                               float32
	Live, Off                                 bool
}

const (
	ParamMixGain          ParamID = 0
	ParamMixPan           ParamID = 1
	ParamMixSendA         ParamID = 2
	ParamMixSendB         ParamID = 3
	ParamMixMute          ParamID = 4
	ParamMixSolo          ParamID = 5
	ParamMixSendPre       ParamID = 6
	ParamMixBus           ParamID = 7
	ParamMixInsert        ParamID = 8
	ParamFxDriveShape     ParamID = 9
	ParamFxDriveGain      ParamID = 10
	ParamFxDriveTone      ParamID = 11
	ParamFxDriveMix       ParamID = 12
	ParamFxDelayTime      ParamID = 13
	ParamFxDelayFeedback  ParamID = 14
	ParamFxDelayDamp      ParamID = 15
	ParamFxDelayPingpong  ParamID = 16
	ParamFxDelayWidth     ParamID = 17
	ParamFxDelayMix       ParamID = 18
	ParamFxReverbSize     ParamID = 19
	ParamFxReverbDecay    ParamID = 20
	ParamFxReverbDamp     ParamID = 21
	ParamFxReverbHighpass ParamID = 22
	ParamFxReverbPredelay ParamID = 23
	ParamFxReverbMix      ParamID = 24
	ParamFxCompDetect     ParamID = 25
	ParamFxCompThreshold  ParamID = 26
	ParamFxCompRatio      ParamID = 27
	ParamFxCompKnee       ParamID = 28
	ParamFxCompAttack     ParamID = 29
	ParamFxCompRelease    ParamID = 30
	ParamFxCompMakeup     ParamID = 31
	ParamFxCompMix        ParamID = 32
	ParamFxCompSidechain  ParamID = 33
	ParamAcidTune         ParamID = 34
	ParamAcidFine         ParamID = 35
	ParamAcidWave         ParamID = 36
	ParamAcidPw           ParamID = 37
	ParamAcidDetune       ParamID = 38
	ParamAcidSub          ParamID = 39
	ParamAcidCutoff       ParamID = 40
	ParamAcidReso         ParamID = 41
	ParamAcidEnvmod       ParamID = 42
	ParamAcidDecay        ParamID = 43
	ParamAcidAccent       ParamID = 44
	ParamAcidDrive        ParamID = 45
	ParamAcidRelease      ParamID = 46
	ParamAcidSlide        ParamID = 47
	ParamAcidGate         ParamID = 48
	ParamAcidFilter       ParamID = 49
	ParamAcidSavage       ParamID = 50
	ParamAcidOctave       ParamID = 51
	ParamDrumBdTune       ParamID = 52
	ParamDrumBdDecay      ParamID = 53
	ParamDrumBdSweep      ParamID = 54
	ParamDrumBdSweepTime  ParamID = 55
	ParamDrumBdClick      ParamID = 56
	ParamDrumBdDrive      ParamID = 57
	ParamDrumBdLevel      ParamID = 58
	ParamDrumBdPan        ParamID = 59
	ParamDrumSdTune       ParamID = 60
	ParamDrumSdTone       ParamID = 61
	ParamDrumSdMix        ParamID = 62
	ParamDrumSdSnappy     ParamID = 63
	ParamDrumSdDecay      ParamID = 64
	ParamDrumSdLevel      ParamID = 65
	ParamDrumSdPan        ParamID = 66
	ParamDrumChTune       ParamID = 67
	ParamDrumChTone       ParamID = 68
	ParamDrumChDecay      ParamID = 69
	ParamDrumChMetal      ParamID = 70
	ParamDrumChLevel      ParamID = 71
	ParamDrumChPan        ParamID = 72
	ParamDrumOhTune       ParamID = 73
	ParamDrumOhTone       ParamID = 74
	ParamDrumOhDecay      ParamID = 75
	ParamDrumOhMetal      ParamID = 76
	ParamDrumOhLevel      ParamID = 77
	ParamDrumOhPan        ParamID = 78
	ParamDrumCpTone       ParamID = 79
	ParamDrumCpDecay      ParamID = 80
	ParamDrumCpSpread     ParamID = 81
	ParamDrumCpLevel      ParamID = 82
	ParamDrumCpPan        ParamID = 83
	ParamDrumRsTune       ParamID = 84
	ParamDrumRsDecay      ParamID = 85
	ParamDrumRsLevel      ParamID = 86
	ParamDrumRsPan        ParamID = 87
	ParamDrumLtTune       ParamID = 88
	ParamDrumLtDecay      ParamID = 89
	ParamDrumLtSweep      ParamID = 90
	ParamDrumLtLevel      ParamID = 91
	ParamDrumLtPan        ParamID = 92
	ParamDrumMtTune       ParamID = 93
	ParamDrumMtDecay      ParamID = 94
	ParamDrumMtSweep      ParamID = 95
	ParamDrumMtLevel      ParamID = 96
	ParamDrumMtPan        ParamID = 97
	ParamDrumHtTune       ParamID = 98
	ParamDrumHtDecay      ParamID = 99
	ParamDrumHtSweep      ParamID = 100
	ParamDrumHtLevel      ParamID = 101
	ParamDrumHtPan        ParamID = 102
	ParamDrumCbTune       ParamID = 103
	ParamDrumCbDecay      ParamID = 104
	ParamDrumCbLevel      ParamID = 105
	ParamDrumCbPan        ParamID = 106
	ParamDrumCyTune       ParamID = 107
	ParamDrumCyDecay      ParamID = 108
	ParamDrumCyTone       ParamID = 109
	ParamDrumCyLevel      ParamID = 110
	ParamDrumCyPan        ParamID = 111
	ParamCount                    = 112
)

var Params = [...]ParamSpec{
	{0, "mix.gain", "track", "level", "dB", "fader", "source", -60, 6, -6, 5, true, true},
	{1, "mix.pan", "track", "pan", "", "linear", "source", -1, 1, 0, 5, true, false},
	{2, "mix.send_a", "track", "send_a", "", "linear", "source", 0, 1, 0, 5, true, false},
	{3, "mix.send_b", "track", "send_b", "", "linear", "source", 0, 1, 0, 5, true, false},
	{4, "mix.mute", "track", "mute", "", "toggle", "live-only", 0, 1, 0, 10, true, false},
	{5, "mix.solo", "track", "solo", "", "toggle", "live-only", 0, 1, 0, 10, true, false},
	{6, "mix.send_pre", "track", "send_pre", "", "toggle", "source", 0, 1, 0, 0, false, false},
	{7, "mix.bus", "track", "bus", "", "enum", "source", 0, 1, 0, 0, false, false},
	{8, "mix.insert", "track", "insert", "", "enum", "source", 0, 1, 0, 0, false, false},
	{9, "fx.drive.shape", "global", "shape", "", "enum", "source", 0, 3, 0, 0, false, false},
	{10, "fx.drive.gain", "global", "gain", "dB", "linear", "source", 0, 36, 0, 5, true, false},
	{11, "fx.drive.tone", "global", "tone", "Hz", "log", "source", 1000, 20000, 12000, 5, true, false},
	{12, "fx.drive.mix", "global", "mix", "ratio", "linear", "source", 0, 1, 1, 5, true, false},
	{13, "fx.delay.time", "global", "time", "ms", "log", "source", 1, 2000, 250, 20, true, false},
	{14, "fx.delay.feedback", "global", "feedback", "ratio", "linear", "source", 0, 0.95, 0.35, 5, true, false},
	{15, "fx.delay.damp", "global", "damp", "Hz", "log", "source", 1000, 16000, 6000, 5, true, false},
	{16, "fx.delay.pingpong", "global", "pingpong", "", "toggle", "source", 0, 1, 0, 5, true, false},
	{17, "fx.delay.width", "global", "width", "ratio", "linear", "source", 0, 1, 1, 5, true, false},
	{18, "fx.delay.mix", "global", "mix", "ratio", "linear", "source", 0, 1, 1, 5, true, false},
	{19, "fx.reverb.size", "global", "size", "ratio", "linear", "source", 0.5, 1.5, 1, 5, true, false},
	{20, "fx.reverb.decay", "global", "decay", "ms", "log", "source", 300, 12000, 2400, 5, true, false},
	{21, "fx.reverb.damp", "global", "damp", "Hz", "log", "source", 2000, 16000, 8000, 5, true, false},
	{22, "fx.reverb.highpass", "global", "highpass", "Hz", "log", "source", 40, 400, 120, 5, true, false},
	{23, "fx.reverb.predelay", "global", "predelay", "ms", "linear", "source", 0, 200, 0, 5, true, false},
	{24, "fx.reverb.mix", "global", "mix", "ratio", "linear", "source", 0, 1, 1, 5, true, false},
	{25, "fx.comp.detect", "global", "detect", "", "enum", "source", 0, 1, 0, 0, false, false},
	{26, "fx.comp.threshold", "global", "threshold", "dB", "linear", "source", -40, 0, -18, 5, true, false},
	{27, "fx.comp.ratio", "global", "ratio", "ratio", "linear", "source", 1, 20, 4, 5, true, false},
	{28, "fx.comp.knee", "global", "knee", "dB", "linear", "source", 0, 12, 6, 5, true, false},
	{29, "fx.comp.attack", "global", "attack", "ms", "log", "source", 0.1, 100, 10, 5, true, false},
	{30, "fx.comp.release", "global", "release", "ms", "log", "source", 10, 1000, 100, 5, true, false},
	{31, "fx.comp.makeup", "global", "makeup", "dB", "linear", "source", -24, 24, 0, 5, true, false},
	{32, "fx.comp.mix", "global", "mix", "ratio", "linear", "source", 0, 1, 1, 5, true, false},
	{33, "fx.comp.sidechain", "global", "sidechain", "", "enum", "source", 0, 1, 0, 0, false, false},
	{34, "acid.tune", "track", "tune", "", "linear", "source", -12, 12, 0, 5, false, false},
	{35, "acid.fine", "track", "fine", "", "linear", "source", -100, 100, 0, 5, false, false},
	{36, "acid.wave", "track", "wave", "", "linear", "source", 0, 1, 0, 5, false, false},
	{37, "acid.pw", "track", "pw", "", "linear", "source", 0.1, 0.9, 0.5, 5, false, false},
	{38, "acid.detune", "track", "detune", "", "linear", "source", 0, 50, 0, 5, false, false},
	{39, "acid.sub", "track", "sub", "", "linear", "source", 0, 1, 0, 5, false, false},
	{40, "acid.cutoff", "track", "cutoff", "Hz", "log", "source", 20, 8000, 600, 3, false, false},
	{41, "acid.reso", "track", "reso", "", "linear", "source", 0, 1, 0.55, 5, false, false},
	{42, "acid.envmod", "track", "envmod", "", "linear", "source", 0, 1, 0.6, 5, false, false},
	{43, "acid.decay", "track", "decay", "ms", "log", "source", 100, 3000, 400, 5, false, false},
	{44, "acid.accent", "track", "accent", "", "linear", "source", 0, 1, 0.7, 5, false, false},
	{45, "acid.drive", "track", "drive", "", "linear", "source", 0, 1, 0.2, 5, false, false},
	{46, "acid.release", "track", "release", "ms", "log", "source", 5, 500, 30, 5, false, false},
	{47, "acid.slide", "track", "slide", "ms", "log", "source", 20, 200, 60, 5, false, false},
	{48, "acid.gate", "track", "gate", "", "linear", "source", 10, 100, 55, 5, false, false},
	{49, "acid.filter", "track", "filter", "", "enum", "source", 0, 1, 0, 0, false, false},
	{50, "acid.savage", "track", "savage", "", "toggle", "source", 0, 1, 0, 0, false, false},
	{51, "acid.octave", "track", "octave", "", "enum", "source", 0, 6, 2, 0, false, false},
	{52, "drum.bd.tune", "track", "bd_tune", "Hz", "log", "source", 40, 120, 55, 5, false, false},
	{53, "drum.bd.decay", "track", "bd_decay", "ms", "log", "source", 80, 1500, 400, 5, false, false},
	{54, "drum.bd.sweep", "track", "bd_sweep", "", "linear", "source", 1, 8, 4, 5, false, false},
	{55, "drum.bd.sweep_time", "track", "bd_sweep_time", "ms", "log", "source", 10, 80, 30, 5, false, false},
	{56, "drum.bd.click", "track", "bd_click", "ratio", "linear", "source", 0, 1, 0.3, 5, false, false},
	{57, "drum.bd.drive", "track", "bd_drive", "ratio", "linear", "source", 0, 1, 0.2, 5, false, false},
	{58, "drum.bd.level", "track", "bd_level", "dB", "fader", "source", -60, 6, -6, 5, false, true},
	{59, "drum.bd.pan", "track", "bd_pan", "", "linear", "source", -1, 1, 0, 5, false, false},
	{60, "drum.sd.tune", "track", "sd_tune", "ratio", "linear", "source", 0.7, 1.4, 1, 5, false, false},
	{61, "drum.sd.tone", "track", "sd_tone", "ratio", "linear", "source", 0.5, 2, 1, 5, false, false},
	{62, "drum.sd.mix", "track", "sd_mix", "ratio", "linear", "source", 0, 1, 0.6, 5, false, false},
	{63, "drum.sd.snappy", "track", "sd_snappy", "ms", "log", "source", 60, 400, 180, 5, false, false},
	{64, "drum.sd.decay", "track", "sd_decay", "ms", "log", "source", 40, 300, 90, 5, false, false},
	{65, "drum.sd.level", "track", "sd_level", "dB", "fader", "source", -60, 6, -6, 5, false, true},
	{66, "drum.sd.pan", "track", "sd_pan", "", "linear", "source", -1, 1, 0, 5, false, false},
	{67, "drum.ch.tune", "track", "ch_tune", "ratio", "linear", "source", 0.8, 1.25, 1, 5, false, false},
	{68, "drum.ch.tone", "track", "ch_tone", "Hz", "log", "source", 5000, 10000, 7500, 5, false, false},
	{69, "drum.ch.decay", "track", "ch_decay", "ms", "log", "source", 20, 150, 60, 5, false, false},
	{70, "drum.ch.metal", "track", "ch_metal", "", "toggle", "source", 0, 1, 0, 5, false, false},
	{71, "drum.ch.level", "track", "ch_level", "dB", "fader", "source", -60, 6, -6, 5, false, true},
	{72, "drum.ch.pan", "track", "ch_pan", "", "linear", "source", -1, 1, 0, 5, false, false},
	{73, "drum.oh.tune", "track", "oh_tune", "ratio", "linear", "source", 0.8, 1.25, 1, 5, false, false},
	{74, "drum.oh.tone", "track", "oh_tone", "Hz", "log", "source", 5000, 10000, 7500, 5, false, false},
	{75, "drum.oh.decay", "track", "oh_decay", "ms", "log", "source", 150, 1200, 400, 5, false, false},
	{76, "drum.oh.metal", "track", "oh_metal", "", "toggle", "source", 0, 1, 0, 5, false, false},
	{77, "drum.oh.level", "track", "oh_level", "dB", "fader", "source", -60, 6, -6, 5, false, true},
	{78, "drum.oh.pan", "track", "oh_pan", "", "linear", "source", -1, 1, 0, 5, false, false},
	{79, "drum.cp.tone", "track", "cp_tone", "Hz", "log", "source", 700, 2000, 1100, 5, false, false},
	{80, "drum.cp.decay", "track", "cp_decay", "ms", "log", "source", 60, 400, 120, 5, false, false},
	{81, "drum.cp.spread", "track", "cp_spread", "ms", "log", "source", 6, 16, 10, 5, false, false},
	{82, "drum.cp.level", "track", "cp_level", "dB", "fader", "source", -60, 6, -6, 5, false, true},
	{83, "drum.cp.pan", "track", "cp_pan", "", "linear", "source", -1, 1, 0, 5, false, false},
	{84, "drum.rs.tune", "track", "rs_tune", "ratio", "linear", "source", 0.7, 1.4, 1, 5, false, false},
	{85, "drum.rs.decay", "track", "rs_decay", "ms", "log", "source", 4, 50, 12, 5, false, false},
	{86, "drum.rs.level", "track", "rs_level", "dB", "fader", "source", -60, 6, -6, 5, false, true},
	{87, "drum.rs.pan", "track", "rs_pan", "", "linear", "source", -1, 1, 0, 5, false, false},
	{88, "drum.lt.tune", "track", "lt_tune", "ratio", "linear", "source", 0.6674199270850172, 1.4983070768766815, 1, 5, false, false},
	{89, "drum.lt.decay", "track", "lt_decay", "ms", "log", "source", 80, 1000, 250, 5, false, false},
	{90, "drum.lt.sweep", "track", "lt_sweep", "ratio", "linear", "source", 0, 2, 0.4, 5, false, false},
	{91, "drum.lt.level", "track", "lt_level", "dB", "fader", "source", -60, 6, -6, 5, false, true},
	{92, "drum.lt.pan", "track", "lt_pan", "", "linear", "source", -1, 1, 0, 5, false, false},
	{93, "drum.mt.tune", "track", "mt_tune", "ratio", "linear", "source", 0.6674199270850172, 1.4983070768766815, 1, 5, false, false},
	{94, "drum.mt.decay", "track", "mt_decay", "ms", "log", "source", 80, 1000, 250, 5, false, false},
	{95, "drum.mt.sweep", "track", "mt_sweep", "ratio", "linear", "source", 0, 2, 0.4, 5, false, false},
	{96, "drum.mt.level", "track", "mt_level", "dB", "fader", "source", -60, 6, -6, 5, false, true},
	{97, "drum.mt.pan", "track", "mt_pan", "", "linear", "source", -1, 1, 0, 5, false, false},
	{98, "drum.ht.tune", "track", "ht_tune", "ratio", "linear", "source", 0.6674199270850172, 1.4983070768766815, 1, 5, false, false},
	{99, "drum.ht.decay", "track", "ht_decay", "ms", "log", "source", 80, 1000, 250, 5, false, false},
	{100, "drum.ht.sweep", "track", "ht_sweep", "ratio", "linear", "source", 0, 2, 0.4, 5, false, false},
	{101, "drum.ht.level", "track", "ht_level", "dB", "fader", "source", -60, 6, -6, 5, false, true},
	{102, "drum.ht.pan", "track", "ht_pan", "", "linear", "source", -1, 1, 0, 5, false, false},
	{103, "drum.cb.tune", "track", "cb_tune", "ratio", "linear", "source", 0.7, 1.4, 1, 5, false, false},
	{104, "drum.cb.decay", "track", "cb_decay", "ms", "log", "source", 40, 400, 120, 5, false, false},
	{105, "drum.cb.level", "track", "cb_level", "dB", "fader", "source", -60, 6, -6, 5, false, true},
	{106, "drum.cb.pan", "track", "cb_pan", "", "linear", "source", -1, 1, 0, 5, false, false},
	{107, "drum.cy.tune", "track", "cy_tune", "ratio", "linear", "source", 0.8, 1.25, 1, 5, false, false},
	{108, "drum.cy.decay", "track", "cy_decay", "ms", "log", "source", 500, 4000, 1500, 5, false, false},
	{109, "drum.cy.tone", "track", "cy_tone", "ratio", "linear", "source", 0.5, 2, 1, 5, false, false},
	{110, "drum.cy.level", "track", "cy_level", "dB", "fader", "source", -60, 6, -6, 5, false, true},
	{111, "drum.cy.pan", "track", "cy_pan", "", "linear", "source", -1, 1, 0, 5, false, false},
}

func Param(id ParamID) (ParamSpec, bool) {
	if int(id) >= len(Params) {
		return ParamSpec{}, false
	}
	return Params[id], true
}
func FindParam(name string) (ParamID, bool) {
	for i := range Params {
		if Params[i].Name == name {
			return ParamID(i), true
		}
	}
	return 0, false
}
