// Package paramdefs loads the checked-in parameter catalog and generates
// language and kernel views from that data.
package paramdefs

import (
	"bytes"
	_ "embed"
	"encoding/json"
	"fmt"
	"go/format"
	"strings"
)

//go:embed registry.json
var registryData []byte

type Descriptor struct {
	ID          string   `json:"id"`
	Path        string   `json:"path"`
	Scope       string   `json:"scope"`
	Voices      []string `json:"voices"`
	Source      string   `json:"source"`
	Unit        string   `json:"unit"`
	Min         float64  `json:"min"`
	Max         float64  `json:"max"`
	Default     float64  `json:"default"`
	Curve       string   `json:"curve"`
	Values      []string `json:"values,omitempty"`
	Off         bool     `json:"off,omitempty"`
	DisplayStep float64  `json:"display_step"`
	SmoothingMS float64  `json:"smoothing_ms"`
	Live        bool     `json:"live"`
	Automatable bool     `json:"automatable"`
	Persist     string   `json:"persist"`
	Schema      string   `json:"schema,omitempty"`
}

// Registry is loaded from the single checked-in data source in stable order;
// its order defines the ParamID ABI.
var Registry = loadRegistry()

func loadRegistry() []Descriptor {
	var rows []Descriptor
	if err := json.Unmarshal(registryData, &rows); err != nil {
		panic(fmt.Errorf("decode parameter registry data: %w", err))
	}
	return rows
}

func GoName(id string) string {
	name := strings.NewReplacer(".", "_", "-", "_").Replace(id)
	parts := strings.Split(name, "_")
	for i := range parts {
		if parts[i] != "" {
			parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
		}
	}
	return strings.Join(parts, "")
}

func GenerateJSON() ([]byte, error) {
	return bytes.Clone(registryData), nil
}

func GenerateKernel() ([]byte, error) {
	var b bytes.Buffer
	fmt.Fprintln(&b, "// Code generated by cmd/paramgen; DO NOT EDIT.")
	fmt.Fprintln(&b, "package kernel")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "type ParamID uint16")
	fmt.Fprintln(&b, "type ParamSpec struct { ID ParamID; Name, Path, Scope, Source, Unit, Curve, Persist string; Min, Max, Default, DisplayStep float32; SmoothingMS float32; Live, Automatable, Off bool }")
	fmt.Fprintln(&b, "const (")
	for i, d := range Registry {
		fmt.Fprintf(&b, "\tParam%s ParamID = %d\n", GoName(d.ID), i)
	}
	fmt.Fprintf(&b, "\tParamCount = %d\n", len(Registry))
	fmt.Fprintln(&b, ")")
	fmt.Fprintln(&b, "var Params = [...]ParamSpec{")
	for i, d := range Registry {
		fmt.Fprintf(&b, "\t{%d, %q, %q, %q, %q, %q, %q, %q, %s, %s, %s, %s, %s, %t, %t, %t},\n",
			i, d.ID, d.Path, d.Scope, d.Source, d.Unit, d.Curve, d.Persist,
			floatLiteral(d.Min), floatLiteral(d.Max), floatLiteral(d.Default), floatLiteral(d.DisplayStep), floatLiteral(d.SmoothingMS),
			d.Live, d.Automatable, d.Off)
	}
	fmt.Fprintln(&b, "}")
	fmt.Fprintln(&b, "func Param(id ParamID) (ParamSpec, bool) { if int(id) >= len(Params) { return ParamSpec{}, false }; return Params[id], true }")
	fmt.Fprintln(&b, "func FindParam(name string) (ParamID, bool) { for i := range Params { if Params[i].Name == name { return ParamID(i), true } }; return 0, false }")
	formatted, err := format.Source(b.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated parameter table: %w", err)
	}
	return formatted, nil
}

func floatLiteral(value float64) string { return fmt.Sprintf("%g", value) }
