package main

import (
	"crypto/sha256"
	"fmt"
	"go/format"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"m31labs.dev/gosx/transpile"
)

func main() {
	source, err := os.ReadFile("app/ui/components.gsx")
	if err != nil {
		log.Fatal(err)
	}
	code, err := transpile.Transpile(source, transpile.Options{SourceFile: "app/ui/components.gsx"})
	if err != nil {
		log.Fatal(err)
	}
	formatted, err := format.Source([]byte("// Code generated by go generate; DO NOT EDIT.\n" + code))
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile("ui/page_gsx.go", formatted, 0644); err != nil {
		log.Fatal(err)
	}
	css, err := os.ReadFile("app/ui/components.css")
	if err != nil {
		log.Fatal(err)
	}
	style := fmt.Sprintf("// Code generated by go generate; DO NOT EDIT.\npackage ui\nvar CSS = []byte(%q)\n", css)
	if err := os.WriteFile("ui/style_asset.go", []byte(style), 0644); err != nil {
		log.Fatal(err)
	}
	if err := os.MkdirAll("build", 0755); err != nil {
		log.Fatal(err)
	}
	command := exec.Command("go", "build", "-trimpath", "-buildvcs=false", "-ldflags=-s -w", "-o", "build/cicada-meters.wasm", "./engine")
	command.Env = append(os.Environ(), "GOOS=js", "GOARCH=wasm", "CGO_ENABLED=0", "GOWORK=off")
	command.Stderr = os.Stderr
	if err := command.Run(); err != nil {
		log.Fatal(err)
	}
	wasm, err := os.ReadFile("build/cicada-meters.wasm")
	if err != nil {
		log.Fatal(err)
	}
	digest := sha256.Sum256(wasm)
	name := fmt.Sprintf("cicada-meters.%x.wasm", digest[:8])
	if err := os.MkdirAll("public/engines", 0755); err != nil {
		log.Fatal(err)
	}
	// Clean only our generated, content-addressed engine assets.
	old, err := filepath.Glob("public/engines/cicada-meters.*.wasm")
	if err != nil {
		log.Fatal(err)
	}
	for _, path := range old {
		if filepath.Base(path) != name && strings.HasPrefix(filepath.Base(path), "cicada-meters.") {
			if err := os.Remove(path); err != nil {
				log.Fatal(err)
			}
		}
	}
	if err := os.WriteFile(filepath.Join("public/engines", name), wasm, 0644); err != nil {
		log.Fatal(err)
	}
	asset := fmt.Sprintf("// Code generated by go generate; DO NOT EDIT.\npackage ui\nconst MeterEnginePath = %q\n", "/engines/"+name)
	if err := os.WriteFile("ui/engine_asset.go", []byte(asset), 0644); err != nil {
		log.Fatal(err)
	}
}
