#!/usr/bin/env python3
"""Train the original CC0 Cicada causal amp; Python/NumPy run outside the kernel."""
import os

for variable in ("OPENBLAS_NUM_THREADS", "OMP_NUM_THREADS", "MKL_NUM_THREADS"):
    os.environ[variable] = "1"

import argparse
import hashlib
import json
from pathlib import Path
import numpy as np

SEED = 20261006
TAPS = 8
HIDDEN = 4


def corpus(seed, frames=65536):
    """Original procedural data: tones, chirps, decaying plucks, noise, impulses."""
    rng = np.random.default_rng(seed)
    chunks = []
    for index in range(64):
        t = np.arange(frames // 64, dtype=np.float64) / 48000
        f = rng.uniform(65, 6000)
        phase = rng.uniform(-np.pi, np.pi)
        signal = np.sin(2 * np.pi * (f * t + rng.uniform(0, 3000) * t * t) + phase)
        signal += .25 * np.sin(2 * np.pi * f * 2.01 * t + phase)
        if index % 4 == 0:
            signal *= np.exp(-t * rng.uniform(10, 100))
        elif index % 4 == 1:
            signal = rng.uniform(-1, 1, len(t))
        elif index % 4 == 2:
            signal += .2 * rng.uniform(-1, 1, len(t))
            signal[::113] += .9
        signal *= rng.uniform(.05, 1.7)
        chunks.append(np.clip(signal, -1, 32767 / 32768))
    audio = np.concatenate(chunks)
    padded = np.pad(audio, (TAPS - 1, 0))
    features = np.stack([padded[TAPS - 1 - k:len(padded) - k] for k in range(TAPS)], axis=1)
    # Fictional two-stage saturation/tone reference, not a hardware capture.
    stages = np.tanh(2.3 * features[:, :4] + .35 * features[:, 1:5] - .15 * features[:, 2:6])
    target = .72 * (.65 * stages[:, 0] + .25 * stages[:, 1] + .10 * stages[:, 3])
    return features, target


def train(steps):
    x, target = corpus(SEED)
    test_x, test_y = corpus(SEED + 1, 32768)
    rng = np.random.default_rng(SEED + 2)
    weights = rng.normal(0, .35, (HIDDEN, TAPS))
    output = rng.normal(0, .2, HIDDEN)
    parameters = [weights, output]
    first = [np.zeros_like(p) for p in parameters]
    second = [np.zeros_like(p) for p in parameters]
    for step in range(1, steps + 1):
        indices = rng.integers(0, len(x), 512)
        batch, expected = x[indices], target[indices]
        hidden = np.tanh(batch @ weights.T)
        error = hidden @ output - expected
        grad_output = hidden.T @ error * (2 / len(batch))
        grad_weights = ((error[:, None] * output * (1 - hidden * hidden)).T @ batch) * (2 / len(batch))
        for index, grad in enumerate((grad_weights, grad_output)):
            first[index] = .9 * first[index] + .1 * grad
            second[index] = .999 * second[index] + .001 * grad * grad
            parameters[index] -= .008 * (first[index] / (1 - .9 ** step)) / (np.sqrt(second[index] / (1 - .999 ** step)) + 1e-8)
            limit = 3.9 if index == 0 else 1.99
            np.clip(parameters[index], -limit, limit, out=parameters[index])
    qweights = np.rint(weights * 4096).astype(np.int16)
    qoutput = np.rint(output * 16384).astype(np.int16)
    table = np.rint(np.tanh(np.arange(257) / 64) * 32767).astype(np.int16)
    quant_input = np.trunc(test_x * 32768).astype(np.int64)
    logits = (quant_input @ qweights.astype(np.int64).T) >> 15
    magnitude = np.minimum(np.abs(logits), 16384)
    index = np.minimum(magnitude >> 6, 255)
    fraction = magnitude - (index << 6)
    hidden = table[index].astype(np.int64) + ((table[index + 1].astype(np.int64) - table[index]) * fraction >> 6)
    hidden *= np.where(logits < 0, -1, 1)
    prediction = np.clip((hidden @ qoutput.astype(np.int64)) >> 14, -32768, 32767) / 32768
    loss = float(np.mean((prediction - test_y) ** 2))
    baseline = float(np.mean(test_y ** 2))
    packed = qweights.astype('<i2').tobytes() + qoutput.astype('<i2').tobytes() + table.astype('<i2').tobytes()
    metadata = {"model": "cicada-causal-amp-v1", "seed": SEED, "steps": steps,
                "training_frames": len(x), "held_out_frames": len(test_x), "sample_rate": 48000,
                "architecture": f"{TAPS}-tap causal convolution, {HIDDEN} tanh channels, linear readout; no biases",
                "quantization": "input/history Q15; convolution Q12; tanh Q15; readout Q14",
                "held_out_quantized_mse": loss, "held_out_quantized_snr_db": float(10 * np.log10(baseline / loss)),
                "parameter_bytes": int(qweights.nbytes + qoutput.nbytes), "activation_table_bytes": int(table.nbytes),
                "sha256_le_i16_weights_output_tanh": hashlib.sha256(packed).hexdigest(),
                "license": "CC0-1.0", "data": "Original procedural audio generated by this script; CC0-1.0"}
    return qweights, qoutput, table, metadata


def go_array(values):
    return ", ".join(str(int(v)) for v in values)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--steps', type=int, default=6000)
    parser.add_argument('--output', type=Path, default=Path('kernel/amp'))
    args = parser.parse_args()
    w, o, table, metadata = train(args.steps)
    args.output.mkdir(parents=True, exist_ok=True)
    source = '// Trained with tools/train-neural-amp.py. Model and procedural training data: CC0-1.0.\npackage amp\n\n'
    source += 'var convolutionWeights = [Hidden][Taps]int16{\n'
    source += ''.join('\t{' + go_array(row) + '},\n' for row in w) + '}\n\n'
    source += 'var outputWeights = [Hidden]int16{' + go_array(o) + '}\n\n'
    source += 'var tanhTable = [257]int16{\n'
    source += ''.join('\t' + go_array(table[i:i+12]) + ',\n' for i in range(0, len(table), 12)) + '}\n'
    (args.output / 'weights.go').write_text(source)
    (args.output / 'model.json').write_text(json.dumps(metadata, indent=2) + '\n')
    print(json.dumps(metadata, indent=2))


if __name__ == '__main__':
    main()
