package sample

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"runtime"
	"sync"
	"testing"
	"time"
)

// A new process is essential: other sample tests may already have constructed
// voices. Never reset the production once guard or tables from a running test.
func TestSRCPreparationLifecycle(t *testing.T) {
	for _, scenario := range []string{"import", "invalid", "voice", "pool", "concurrent"} {
		t.Run(scenario, func(t *testing.T) {
			ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
			defer cancel()
			command := exec.CommandContext(ctx, os.Args[0], "-test.run=^TestSRCPreparationFreshProcess$", "-test.v")
			command.Env = append(os.Environ(), "CICADA_SRC_PREPARATION_TEST="+scenario)
			if output, err := command.CombinedOutput(); err != nil {
				t.Fatalf("fresh %s process: %v\n%s", scenario, err, output)
			} else {
				t.Logf("%s", output)
			}
		})
	}
}

func TestSRCPreparationFreshProcess(t *testing.T) {
	scenario := os.Getenv("CICADA_SRC_PREPARATION_TEST")
	if scenario == "" {
		t.Skip("invoked only by the lifecycle test in a fresh process")
	}
	empty := func() {
		t.Helper()
		for i := range banks {
			if banks[i].coeff != nil {
				t.Fatalf("bank %d allocated before a valid constructor", i)
			}
		}
	}
	empty()
	if scenario == "import" {
		// The realtime lookup is deliberately pure even before preparation.
		for _, ratio := range []float64{.125, 1, 1.125, 1.25, 1.5, 2, 3, 4, 8} {
			if bankFor(ratio) == nil {
				t.Fatal("missing bank metadata")
			}
		}
		empty()
		return
	}
	region := testRegion(1024, true, true)
	if scenario == "invalid" {
		for _, rate := range []int{0, 8000, 192000} {
			if _, err := New(rate, region); err == nil {
				t.Fatal("invalid voice output rate accepted")
			}
			if _, err := NewPool(rate, 2, region); err == nil {
				t.Fatal("invalid pool output rate accepted")
			}
		}
		for _, maximum := range []int{0, MaxVoices + 1} {
			if _, err := NewPool(48000, maximum, region); err == nil {
				t.Fatal("invalid pool maximum accepted")
			}
		}
		if _, err := New(48000, Region{}); err == nil {
			t.Fatal("invalid voice region accepted")
		}
		if _, err := NewPool(48000, 2, Region{}); err == nil {
			t.Fatal("invalid pool region accepted")
		}
		empty()
		return
	}
	var voice *Voice
	var pool *Pool
	var err error
	switch scenario {
	case "voice":
		voice, err = New(48000, region)
	case "pool":
		pool, err = NewPool(48000, 2, region)
	case "concurrent":
		const constructors = 16
		var errors [constructors]error
		var group sync.WaitGroup
		start := make(chan struct{})
		for i := range errors {
			group.Add(1)
			go func() {
				defer group.Done()
				<-start
				if i%2 == 0 {
					_, errors[i] = New(48000, region)
				} else {
					_, errors[i] = NewPool(48000, 2, region)
				}
			}()
		}
		close(start)
		group.Wait()
		for _, err := range errors {
			if err != nil {
				t.Fatal(err)
			}
		}
	default:
		t.Fatalf("unknown lifecycle scenario %q", scenario)
	}
	if err != nil {
		t.Fatal(err)
	}
	var pointers [len(banks)]*float32
	total := 0
	for i := range banks {
		if len(banks[i].coeff) != (phases+1)*banks[i].taps {
			t.Fatalf("bank %d incomplete after constructor", i)
		}
		pointers[i] = &banks[i].coeff[0]
		total += len(banks[i].coeff)
	}
	if total != 2152500 {
		t.Fatalf("coefficient count=%d", total)
	}
	if voice == nil {
		voice, err = New(48000, region)
		if err != nil {
			t.Fatal(err)
		}
	}
	if pool == nil {
		pool, err = NewPool(48000, 2, region)
		if err != nil {
			t.Fatal(err)
		}
	}
	var left, right [128]float32
	// Measure the first note and render, not an AllocsPerRun warmup that could
	// hide a first-use preparation. All buffers and MemStats are ready already.
	// MemStats counts allocations from every goroutine, so use one processor,
	// as AllocsPerRun does, and finish setup's GC work before measuring.
	previousProcs := runtime.GOMAXPROCS(1)
	t.Cleanup(func() { runtime.GOMAXPROCS(previousProcs) })
	runtime.GC()
	var before, after runtime.MemStats
	runtime.ReadMemStats(&before)
	voiceErr := voice.NoteOn(67, 127)
	_, poolErr := pool.NoteOn(67, 127)
	voice.Render(left[:], right[:])
	pool.Render(left[:], right[:])
	runtime.ReadMemStats(&after)
	if voiceErr != nil || poolErr != nil {
		t.Fatalf("first notes: %v, %v", voiceErr, poolErr)
	}
	if after.Mallocs != before.Mallocs {
		t.Fatalf("first NoteOn/render allocated %d times", after.Mallocs-before.Mallocs)
	}
	for i := range banks {
		if &banks[i].coeff[0] != pointers[i] {
			t.Fatalf("bank %d regenerated by later constructor or callback", i)
		}
	}
	fmt.Printf("METRIC SRC_PREPARATION scenario=%s banks=%d coefficients=%d first_note_render_allocations=0\n", scenario, len(banks), total)
}
